// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ie9YYCn3tcklHVVhxPWohsP-cuC2tLU',
    appId: '1:873987138688:web:a6cdc43ac440aa71687265',
    messagingSenderId: '873987138688',
    projectId: 'finale-a7481',
    authDomain: 'finale-a7481.firebaseapp.com',
    storageBucket: 'finale-a7481.firebasestorage.app',
    measurementId: 'G-GZ14GZ754M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLqR369XZcM-w5utfKfzYx-h3hb6fygGw',
    appId: '1:873987138688:android:1d94982f7e27111d687265',
    messagingSenderId: '873987138688',
    projectId: 'finale-a7481',
    storageBucket: 'finale-a7481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03Eut8ErL4GNjd5gfTbLPL4_V6vIO_j0',
    appId: '1:873987138688:ios:f0633fdec40cf61e687265',
    messagingSenderId: '873987138688',
    projectId: 'finale-a7481',
    storageBucket: 'finale-a7481.firebasestorage.app',
    iosBundleId: 'com.example.finale',
  );

}